use HVACIssues2018_01;

#Fill Buildings
insert into Building (Id, BuildingName) values (1, 'SE 2');

#Fill Floors
insert into Floor (BuildingId, FloorNumber, FloorName) values (1, 0, 'Basement');
insert into Floor (BuildingId, FloorNumber, FloorName) values (1, 1, 'First Floor');
insert into Floor (BuildingId, FloorNumber, FloorName) values (1, 2, 'Second Floor');
insert into Floor (BuildingId, FloorNumber, FloorName) values (1, 3, 'third Floor');

#Fill Rooms
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 0, 1, 'Room 90D');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 0, 2, 'Room 90E');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 0, 3, 'Room 90C');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 0, 4, 'Room 90F');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 0, 5, 'Room 90G');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 0, 6, 'Room 90B');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 0, 7, 'Room 090');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 0, 8, 'Room 90A');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 0, 9, 'Room 0C9');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 0, 10, 'Room 85');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 0, 11, 'Room 80 West');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 0, 12, 'Room 80 East');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 0, 13, 'Room 80B');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 0, 14, 'Room 80F');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 0, 15, 'Room 80G');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 0, 16, 'Room 80C');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 0, 17, 'Room 80E');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 0, 18, 'Room 80D');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 0, 19, 'Room 80A');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 0, 20, 'Room 70');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 0, 21, 'Room 060');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 0, 22, 'Room 50 West');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 0, 23, 'Room 50 East');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 0, 24, 'Room 50G');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 0, 25, 'Room 50H');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 0, 26, 'Room 50D');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 0, 27, 'Room 50F');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 0, 28, 'Room 50E');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 0, 29, 'Room 50C');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 0, 30, 'Room 50B');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 0, 31, 'Room 50A');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 0, 32, 'Room 40');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 0, 33, 'Room 30');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 0, 34, 'Room 0C6B');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 0, 35, 'Room 01');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 0, 36, 'Room 02');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 0, 37, 'Room 0C1');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 0, 38, 'Room 24');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 0, 39, 'Room 20');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 0, 40, 'Room 20C');

insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 1, 41, 'Room 190');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 1, 42, 'Room 180');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 1, 43, 'Room 170');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 1, 44, 'Room 160 West');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 1, 45, 'Room 160 East');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 1, 46, 'Room 150 East');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 1, 47, 'Room 150 West');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 1, 48, 'Room 140');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 1, 49, 'Room 130 East');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 1, 50, 'Room 130 West');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 1, 51, 'Room 155');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 1, 52, 'Room 165 East');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 1, 53, 'Room 165 West');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 1, 54, 'Room 175');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 1, 55, 'Room 185 East');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 1, 56, 'Room 185 West');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 1, 57, 'Room 1M2');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 1, 58, 'Room IU2');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 1, 59, 'Room 135');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 1, 60, 'Room 1C1A');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 1, 61, 'Room 1C6');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 1, 62, 'Room 102');
//?
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 1, 63, 'Room 110');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 1, 64, 'Room 120C');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 1, 65, 'Room 120D');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 1, 66, 'Room 120E');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 1, 67, 'Room 120F');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 1, 68, 'Room 120G');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 1, 69, 'Room 120A-1');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 1, 70, 'Room 120A-2');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 1, 71, 'Room 120A-3');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 1, 72, 'Room 120B-1');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 1, 73, 'Room 120B-2');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 1, 74, 'Room 120B-3');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 1, 75, 'Room 120H');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 1, 76, 'Room 120J');
//insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 1, 57, 'Room 102A-1');
//insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 1, 57, 'Room 102A-2');
//insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 1, 57, 'Room 102A-3');
//insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 1, 57, 'Room 102A-4');
//insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 1, 57, 'Room 102A-5');
//insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 1, 57, 'Room 110A');
//insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 1, 57, 'Room 120H-1');
//insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 1, 57, 'Room 120H-2');
//insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 1, 57, 'Room 120J-1');
//insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 1, 57, 'Room 120J-2');

insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 2, 77, 'Room 293');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 2, 78, 'Room 292');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 2, 79, 'Room 291');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 2, 80, 'Room 290');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 2, 81, 'Room 2C9');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 2, 82, 'Room 265');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 2, 83, 'Room 230N');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 2, 84, 'Room 230P');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 2, 85, 'Room 230Q');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 2, 86, 'Room 230M');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 2, 87, 'Room 230K');
//?
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 2, 88, 'Hallway 230 SAV-2A10-C');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 2, 89, 'Room 230R');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 2, 90, 'Room 230J');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 2, 91, 'Room 230S');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 2, 92, 'Room 230T');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 2, 93, 'Room 230U');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 2, 94, 'Room 230V');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 2, 95, 'Room 230E');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 2, 96, 'Room 230D');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 2, 97, 'Room 230H');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 2, 98, 'Room 230F');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 2, 99, 'Room 230C');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 2, 100, 'Room 230A');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 2, 101, 'Room 2M2');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 2, 102, 'Room 2U1');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 2, 103, 'Room 286');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 2, 104, 'Room 285');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 2, 105, 'Room 284');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 2, 106, 'Room 283');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 2, 107, 'Room 282');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 2, 108, 'Room 281');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 2, 109, 'Room 280');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 2, 110, 'Room 279');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 2, 111, 'Room 278');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 2, 112, 'Room 277');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 2, 113, 'Room 276');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 2, 114, 'Room 275');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 2, 115, 'Room 274');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 2, 116, 'Room 273');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 2, 117, 'Room 272');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 2, 118, 'Room 271');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 2, 119, 'Room 270');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 2, 120, 'Room 2C7');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 2, 121, 'Room 2C1A');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 2, 122, 'Room 2C6');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 2, 123, 'Room 213C');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 2, 124, 'Room 213D');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 2, 125, 'Room 213E');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 2, 126, 'Room 213B');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 2, 127, 'Room 213A');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 2, 128, 'Room 213F');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 2, 129, 'Room 219');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 2, 130, 'Room 218');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 2, 131, 'Room 2C5');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 2, 132, 'Room 2C4');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 2, 133, 'Room 2C3');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 2, 134, 'Room 224');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 2, 135, 'Room 223');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 2, 136, 'Room 222');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 2, 137, 'Room 221');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 2, 138, 'Room 220');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 2, 139, 'Room 2C2');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 2, 140, 'Room 205');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 2, 141, 'Room 206');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 2, 142, 'Room 207');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 2, 143, 'Room 208');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 2, 144, 'Room 209');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 2, 145, 'Room 210');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 2, 146, 'Room 211');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 2, 147, 'Room 212');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 2, 148, 'Room 214');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 2, 149, 'Room 215');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 2, 150, 'Room 216');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 2, 151, 'Room 217');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 2, 232, 'Hallway 213');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 2, 233, 'Room 213HW');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 2, 234, 'Hallway 230 SAV-2A17-A');

//third floor
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 3, 152, 'Room 393');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 3, 153, 'Room 392');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 3, 154, 'Room 391');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 3, 155, 'Room 390');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 3, 156, 'Room 3C9');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 3, 157, 'Room 365');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 3, 158, 'Room 340R');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 3, 159, 'Room 340Q');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 3, 160, 'Room 340P');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 3, 161, 'Room 340N');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 3, 162, 'Room 340 West');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 3, 163, 'Room 340 Center');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 3, 164, 'Room 340 East');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 3, 165, 'Room 340L');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 3, 166, 'Room 340J');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 3, 167, 'Room 340H');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 3, 168, 'Room 340G');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 3, 169, 'Room 340F');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 3, 170, 'Room 355');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 3, 171, 'Room 340C');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 3, 172, 'Room 340D');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 3, 173, 'Room 340B');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 3, 174, 'Room 335');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 3, 175, 'Room 330');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 3, 176, 'Room 3U1');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 3, 177, 'Room 386');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 3, 178, 'Room 385');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 3, 179, 'Room 384')
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 3, 180, 'Room 383');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 3, 181, 'Room 382');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 3, 182, 'Room 381');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 3, 183, 'Room 380');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 3, 184, 'Room 379');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 3, 185, 'Room 378');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 3, 186, 'Room 377');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 3, 187, 'Room 376');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 3, 188, 'Room 375');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 3, 189, 'Room 374');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 3, 190, 'Room 373');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 3, 191, 'Room 372');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 3, 192, 'Room 371');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 3, 193, 'Room 370');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 3, 194, 'Room 3C7');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 3, 195, 'Room 3C6');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 3, 196, 'Room 3C1');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 3, 197, 'Room 301');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 3, 198, 'Room 3C2');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 3, 199, 'Room 310');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 3, 200, 'Room 305-B');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 3, 201, 'Room 305-C');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 3, 202, 'Room 305-A');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 3, 203, 'Room 310');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 3, 204, 'Room 310A');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 3, 205, 'Room 310B');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 3, 206, 'Room 310C');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 3, 207, 'Room 315E');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 3, 208, 'Room 315F');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 3, 209, 'Room 315G');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 3, 210, 'Room 315H');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 3, 211, 'Room 310E');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 3, 212, 'Room 310D');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 3, 213, 'Room 312');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 3, 214, 'Room 315D');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 3, 215, 'Room 315C');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 3, 216, 'Room 315B');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 3, 217, 'Room 315A');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 3, 218, 'Room 315');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 3, 219, 'Room 3C3');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 3, 220, 'Room 311');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 3, 221, 'Room 313');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 3, 222, 'Room 314');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 3, 223, 'Room 301');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 3, 224, 'Room 302');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 3, 225, 'Room 3C4');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 3, 226, 'Room 325');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 3, 227, 'Room 324');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 3, 228, 'Room 323');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 3, 229, 'Room 322');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 3, 230, 'Room 321');
insert into Room (BuildingId, FloorNumber, RoomId, RoomName) values (1, 3, 231, 'Room 320');
